### ISSUE TITLE
Requirement Engineering

### ISSUE THREAD

**Issue by ObertShen** [ObertShen/Lessons#2]
陶大江老师的需求工程课

**Comment by ObertShen** [comment]
#### 团队作业：
- 订单管理系统的SRS文档
- 团队产品的MRD文档

**Comment by ObertShen** [comment]
#### 团队产品：

乐聚😄

> 问题

有时很想出去吃饭但是没有人一起去。

> 需求

我们能够发送自己的吃饭需求，系统会给我们自动匹配上吃饭的人，并定好地点和时间，大家可以一起愉快的吃一顿饭。

> 功能点
- 用户注册功能 ：学生证注册，现有用户邀请；
- 活动发布功能： 能够发布一条吃饭活动，包括吃饭时间、口味、价位、地点（可以确定一家餐厅），以及对吃饭对象的人数、性别、爱好、专业、年龄等条件的大致筛选；
- 饭后活动功能 ：提供饭后桌游推荐（集成诸如狼人杀、真心话大冒险、谁是卧底等桌游功能），还可以提供饭后活动地点推荐（如附近的KTV，酒吧等等）；
- 用户评价功能：信用级评分和黑名单，举个🌰：如果用户无理由迟到或者不去已经接受的活动，同一活动的用户可对该用户进行投诉，导致其信用级降低，信用级较高的用户优先匹配。用户被举报传销、传教或者态度极差会被加入系统黑名单不能再参与活动。

**Comment by ObertShen** [comment]
#### 盈利点

会员业务

**Comment by Amose-Yao** [comment]
但从现在的描述来看，赢利点还没理解，套路的话就是积累用户人数，让我们的使用人数达到一定数量的时候，发一些类似于广告的东西进行营利，对此，我们首先要解决怎么增强用户粘性

**Comment by Amose-Yao** [comment]
或者说能不能和线下的桌游，KTV合作，在我们平台上注册并且结伴去他们那儿的可以有优惠，然后在我们平台上，类似于小黄车的交一些费用

**Comment by vivianwangyu** [comment]
目标市场概述
    本产品可推广的市场众多，各职业、各年龄阶层均可使用，包括厌倦了独自进餐的群体、想借约饭了解其他领域情报的群体、想通过约饭认识更多新朋友的群体、想通过约饭和饭后娱乐活动放松心情的群体、想约上几个小伙伴一起尝试新鲜的菜品的群体等等。

**Comment by vivianwangyu** [comment]
3.1目标市场概述
	目前我们的___app的主要发展的目标人群为高校校园学生，推广成功后考虑面向全部智能手机用户，学生的身份较容易实名，且高校学生素质水平起点较高。随着工作、学习生活压力愈发繁重，人与人的饮食口味差距又不尽相同，而类似北京的一线城市规模较大，交通的时间金钱成本较高，身边能约饭的人或许吃不到一块去，吃得到一块的人时间或地域又往往难以协调，因此，用来和口味相投、空闲时间相同的人约饭的app受到了使用者的欢迎。然而目前市场上尚未有一款能实现完整功能闭环的一款app，因此，如何实现完整的约饭功能，如何做到精确匹配，如何做到精确推荐成为用户注重的目标。我们面向的市场十分广阔。主要有：
	首先，厌倦自己一个人吃饭的人群。这些人想约饭时，只需打开我们的____app，填写筛选条件（包括时间、口味、价位、地点、餐馆类型，以及共同约饭的人数、性别、爱好、专业、年龄层等），发布约饭需求，即可通过app的精确匹配功能匹配到令你满意的约饭饭局，无需再经历因翻遍各种社交软件的通讯录也找不到一个可以约饭的小伙伴而叹息的尴尬囧事。
	第二，希望通过饭局对其他领域的情报有所了解、对感兴趣却又不熟悉的领域想要有所涉猎的人群。在知识爆炸而又分工精细化的时代，工作中常常遇到跨界问题，因此希望通过饭局涉猎其他领域的机智小伙伴也越来越多，他们喜欢丰富自身的知识库，从而开辟一片新的领域，这时，打开我们提供的app，填写筛选条件，即可为你匹配到令人眼界大开的饭局，为你打开新一扇窗。
	第三，想要结识新朋友的群体。
	第四，想约上一群小伙伴一起尝试新鲜菜品的群体。
	第五，想通过约饭和饭后娱乐活动放松心情的群体。在繁重的学习工作之余，会有一群人相约上一群爱玩的小伙伴欢脱一番，这时，只需打开我们的约饭app，填写筛选条件，即可为你匹配到合适的饭局并为你推荐合适的饭后活动或饭后娱乐场所。
